const seed={FRUTAS:[["Cereza",100],["Tuna",30],["Mango",35],["Guayaba",38],["Fresa",45],["Naranja sin semilla",45],["Uva verde",90],["Manzana gala",55],["Manzana verde",60],["Manzana amarilla",25],["Melón chino",33],["Papaya",30],["Piña miel",35],["Plátano",23],["Plátano macho",38],["Pera",50],["Plátano dominico",38],["Frambuesa",34],["Zarzamora",34],["Bluberry",44],["Sandia",30],["fritura Plátano",35],["Pulpa de diferentes frutas",20],["kiwi",85],["Jicama",31],["Mandarina",50]],VERDURAS:[["Camote",43],["Betabel",25],["Verduura picada",25],["Pulpa para agua",20],["Fresa congelada",50],["Brocoli",35],["Jitomate",26],["Calabaza",18],["Cebolla",35],["Cebolla morada",25],["Cilantro",5],["Chayote",25],["Chile serrano",50],["Chile Jalapeño",40],["Chile poblano",47],["Chile hungaro",77],["Chile morrón verde",90],["Col",20],["Col morada",23],["Elote",15],["Elote amarillo",55],["Cebolla cambray",38],["Champiñones",40],["Nopal",41],["Ejote",50],["Espinaca",78],["Chile güero",60],["Jengibre",140],["Limón c/s",43],["Limón s/s",23],["Lechuga",28],["Oreganoo",5],["Papa",48],["Perejil",5],["Yerbabuena",5],["Rábanos",50],["Zanahoria",17],["Apio",50],["Aguacate",83],["Tomate",20],["Coliflor",35],["Chile Habanero",180],["Verdolaga",40],["Pepino",32]],"MARISCOS & CARNE/S":[["ATÚN",70],["CAMARON SECO",400],["CAMARON",255],["PESCADO",165],["MARLIN",280],["SURIMI",16],["ARRACHERA",180],["ADOBADA",180],["K-TIRAS",210],["BONELESS",170],["PAPA CON FORMA DE CARITA FELIZ",160]],OTROS:[["Ajo",150],["Avena",28],["Tajin",115],["Piloncillo",70],["chia",150],["canela",13],["Consome en polvo",60],["Almendras",450],["Almendra fileteada",350],["Nuez picada",360],["Nuez mitad",600],["Garbanzo",60],["Azucar",26],["Arroz",28],["Frijo",35],["Paprica",115],["Pistache",393],["Ciruela pasa",250],["Chile de arbol",220],["Arándano deshidratado",200],["Coco blanco",180],["Coco tostado",200],["Miel",100],["huevo ranchero",43],["Fruta Seca",229],["Jamaica Colima",250],["Jamaica Sudan",250]]};
let data=JSON.parse(localStorage.getItem('ivettData')||JSON.stringify(seed)),cat=Object.keys(data)[0],over=JSON.parse(localStorage.getItem('ivettImgs')||'{}');
const kw={'Verduura picada':'mixed-vegetables','Pulpa para agua':'fruit-juice','Fresa congelada':'frozen-strawberries','Chile Jalapeño':'jalapeno','Chile hungaro':'green-chili','Chile morrón verde':'green-bell-pepper','Limón c/s':'lime','Limón s/s':'lime','Oreganoo':'oregano','CAMARON SECO':'dried-shrimp','CAMARON':'shrimp','MARLIN':'marlin-fish','SURIMI':'surimi','ARRACHERA':'skirt-steak','ADOBADA':'marinated-meat','K-TIRAS':'beef-strips','BONELESS':'boneless-chicken','PAPA CON FORMA DE CARITA FELIZ':'smiley-potato','Consome en polvo':'bouillon-powder','Frijo':'beans','Jamaica Colima':'hibiscus','Jamaica Sudan':'hibiscus','fritura Plátano':'banana-chips','Pulpa de diferentes frutas':'fruit-pulp','Bluberry':'blueberry'};
function slug(s){return(kw[s]||s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').toLowerCase()}
function img(s){return over[s]||`https://images.weserv.nl/?url=loremflickr.com/240/160/${encodeURIComponent(slug(s))}&w=240&h=160&fit=contain&output=jpg`}
function save(){localStorage.setItem('ivettData',JSON.stringify(data))}
function status(m,err=false){const e=document.getElementById('status');e.textContent=m;e.style.color=err?'#b3261e':'#0b6b2d';clearTimeout(status.t);status.t=setTimeout(()=>e.textContent='',2600)}
function saveI(){try{localStorage.setItem('ivettImgs',JSON.stringify(over));return true}catch(e){console.error(e);status('No hay espacio para guardar más imágenes.',true);return false}}
async function compressImage(file,maxW=480,maxH=360,quality=.78){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{let w=im.naturalWidth,h=im.naturalHeight,scale=Math.min(1,maxW/w,maxH/h);w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality))};im.src=fr.result};fr.readAsDataURL(file)})}
function tabs(){const e=document.getElementById('cats');e.innerHTML='';Object.keys(data).forEach(c=>{const b=document.createElement('button');b.textContent=c;b.className=c===cat?'active':'';b.onclick=()=>{cat=c;render()};e.appendChild(b)})}
function catalog(){const a=data[cat],n=a.length,cols=n>38?4:n>24?4:n>14?3:2,rows=Math.ceil(n/cols),g=document.getElementById('catalog');g.style.gridTemplateColumns=`repeat(${cols},1fr)`;g.style.gridTemplateRows=`repeat(${rows},1fr)`;g.innerHTML='';a.forEach(([nm,p])=>{const d=document.createElement('div');d.className='prod';d.innerHTML=`<img src="${img(nm)}" crossorigin="anonymous"><div class="pn">${nm}</div><div class="price">$${p}</div>`;g.appendChild(d)});document.getElementById('catTitle').textContent=cat;const hp=document.getElementById('heroPhoto');hp.innerHTML='';a.slice(0,6).forEach(([nm])=>{const im=document.createElement('img');im.src=img(nm);im.crossOrigin='anonymous';hp.appendChild(im)})}
function editor(){const q=document.getElementById('search').value.toLowerCase(),e=document.getElementById('editor');e.innerHTML='';data[cat].forEach(it=>{if(!it[0].toLowerCase().includes(q))return;const r=document.createElement('div');r.className='row';r.innerHTML=`<img src="${img(it[0])}"><input value="${it[0].replace(/"/g,'&quot;')}"><input type="number" min="0" value="${it[1]}"><button class="imgbtn">Cambiar imagen</button>`;const ins=r.querySelectorAll('input'),th=r.querySelector('img');ins[0].onchange=x=>{const old=it[0],neu=x.target.value.trim()||old;if(old!==neu&&over[old]){over[neu]=over[old];delete over[old];saveI()}it[0]=neu;save();render()};ins[1].oninput=x=>{it[1]=Number(x.target.value||0);save();catalog()};r.querySelector('button').onclick=()=>pickImage(it,th);e.appendChild(r)})}
function pickImage(it,thumb){const f=document.createElement('input');f.type='file';f.accept='image/*';f.onchange=async()=>{const file=f.files&&f.files[0];if(!file)return;status('Procesando imagen…');try{const result=await compressImage(file),key=it[0],prev=over[key];over[key]=result;if(!saveI()){if(prev)over[key]=prev;else delete over[key];return}thumb.src=result;catalog();status('Imagen actualizada correctamente')}catch(err){console.error(err);status('No se pudo procesar esa imagen.',true)}finally{f.remove()}};document.body.appendChild(f);f.click()}
function render(){tabs();editor();catalog()}
function resetAdd(){document.getElementById('newName').value='';document.getElementById('newPrice').value='';document.getElementById('newImage').value='';document.getElementById('newImageName').textContent=''}
document.getElementById('addToggle').onclick=()=>document.getElementById('addForm').classList.toggle('open');document.getElementById('addCancel').onclick=()=>{resetAdd();document.getElementById('addForm').classList.remove('open')};document.getElementById('newImage').onchange=e=>document.getElementById('newImageName').textContent=e.target.files?.[0]?.name||'';document.getElementById('addSave').onclick=async()=>{const name=document.getElementById('newName').value.trim(),price=Number(document.getElementById('newPrice').value),file=document.getElementById('newImage').files?.[0];if(!name)return status('Escribe el nombre del producto.',true);if(!Number.isFinite(price)||price<0)return status('Escribe un precio válido.',true);if(data[cat].some(x=>x[0].toLowerCase()===name.toLowerCase()))return status('Ese producto ya existe en esta categoría.',true);data[cat].push([name,price]);save();if(file){try{over[name]=await compressImage(file);saveI()}catch(e){console.error(e)}}resetAdd();document.getElementById('addForm').classList.remove('open');render();status(`Producto agregado a ${cat}`)};
document.getElementById('search').oninput=editor;document.getElementById('preview').onclick=()=>document.getElementById('sheet').scrollIntoView({behavior:'smooth'});document.getElementById('print').onclick=()=>window.print();document.getElementById('jpg').onclick=async()=>{const el=document.getElementById('sheet'),t=document.createElement('div');t.className='export-toast';t.textContent='Generando JPG en alta calidad…';document.body.appendChild(t);try{if(document.fonts&&document.fonts.ready)await document.fonts.ready;await new Promise(r=>setTimeout(r,180));const c=await html2canvas(el,{scale:2,useCORS:true,allowTaint:true,backgroundColor:'#fffdf8',logging:false,width:1536,height:1024,windowWidth:1536,windowHeight:1024}),a=document.createElement('a');a.href=c.toDataURL('image/jpeg',.98);a.download='Fruteria_Ivett_'+cat.replace(/[^A-Za-z0-9]+/g,'_')+'_Alta_Calidad.jpg';a.click();t.textContent='JPG listo'}catch(e){console.error(e);t.textContent='No se pudo generar el JPG'}finally{setTimeout(()=>t.remove(),1600)}};render();
