let customers=JSON.parse(localStorage.getItem('ivettCustomers')||'[]'),customerTypeFilter='Todos';
function customerSave(){localStorage.setItem('ivettCustomers',JSON.stringify(customers));if(typeof scheduleCloud==='function')scheduleCloud()}
function customerEsc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showCustomers(){['catalogPanel','promoPanel','inventoryPanel','salesPanel'].forEach(id=>document.getElementById(id)?.classList.add('hidden'));['sheet','promoSheet','saleNote'].forEach(id=>document.getElementById(id)?.classList.add('hidden'));document.getElementById('customersPanel').classList.remove('hidden');document.querySelectorAll('.mi').forEach(x=>x.classList.remove('active'));document.getElementById('menuCustomers').classList.add('active');customerRender()}
function customerRender(){const q=(document.getElementById('customerSearch')?.value||'').toLowerCase(),e=document.getElementById('customerRows');if(!e)return;const list=customers.filter(c=>(customerTypeFilter==='Todos'||(c.type||'Cliente mostrador')===customerTypeFilter)&&[c.name,c.phone,c.address,c.notes,c.type].some(v=>String(v||'').toLowerCase().includes(q)));const title=document.getElementById('customerListTitle');if(title)title.textContent=customerTypeFilter==='Todos'?'Todos los clientes':customerTypeFilter;document.querySelectorAll('.customerTabs button').forEach(b=>b.classList.toggle('active',b.dataset.type===customerTypeFilter));e.innerHTML=list.length?list.map(c=>`<div class="customerRow"><div><b>${customerEsc(c.name)}</b><small>${customerEsc(c.phone||'Sin celular')}</small><em class="customerBadge">${customerEsc(c.type||'Cliente mostrador')}</em></div><span>${customerEsc(c.address||'Sin domicilio')}</span><span>${customerEsc(c.payment||'Efectivo')}</span><div class="customerActions"><button data-use="${c.id}">🧾 Nota</button><button data-edit="${c.id}">✎</button><button class="danger" data-del="${c.id}">×</button></div></div>`).join(''):'<div class="customerEmpty">No hay clientes en este catálogo.</div>';e.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>customerUse(b.dataset.use));e.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>customerEdit(b.dataset.edit));e.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>customerDelete(b.dataset.del))}
function customerClear(){document.getElementById('customerId').value='';['customerName','customerPhone','customerAddress','customerNotes'].forEach(id=>document.getElementById(id).value='');document.getElementById('customerType').value='Cliente mostrador';document.getElementById('customerPayment').value='Efectivo';document.getElementById('customerSaveBtn').textContent='＋ Dar de alta cliente'}
function customerUpsert(){const id=document.getElementById('customerId').value,name=document.getElementById('customerName').value.trim();if(!name)return alert('Escribe el nombre del cliente.');const c={id:id||('C'+Date.now()),name,phone:document.getElementById('customerPhone').value.trim(),address:document.getElementById('customerAddress').value.trim(),type:document.getElementById('customerType').value,payment:document.getElementById('customerPayment').value,notes:document.getElementById('customerNotes').value.trim(),updated:new Date().toISOString()};const i=customers.findIndex(x=>x.id===id);if(i>=0)customers[i]=c;else customers.unshift(c);customerSave();customerClear();customerFillSaleSelect();customerRender()}
function customerEdit(id){const c=customers.find(x=>x.id===id);if(!c)return;document.getElementById('customerId').value=c.id;document.getElementById('customerName').value=c.name||'';document.getElementById('customerPhone').value=c.phone||'';document.getElementById('customerAddress').value=c.address||'';document.getElementById('customerType').value=c.type||'Cliente mostrador';document.getElementById('customerPayment').value=c.payment||'Efectivo';document.getElementById('customerNotes').value=c.notes||'';document.getElementById('customerSaveBtn').textContent='Guardar cambios';window.scrollTo({top:0,behavior:'smooth'})}
function customerDelete(id){const c=customers.find(x=>x.id===id);if(!c||!confirm(`¿Eliminar a ${c.name} del catálogo de clientes?`))return;customers=customers.filter(x=>x.id!==id);customerSave();customerFillSaleSelect();customerRender()}
function customerUse(id){const c=customers.find(x=>x.id===id);if(!c)return;showSales();const sel=document.getElementById('saleCustomer');if(sel){sel.value=id;sel.dispatchEvent(new Event('change'))}}
function customerFillSaleSelect(){const s=document.getElementById('saleCustomer');if(!s)return;const keep=s.value,groups=['Cliente preferencial','Cliente mayorista','Cliente mostrador','Cliente a domicilio'];s.innerHTML='<option value="">— Cliente de mostrador / capturar manual —</option>'+groups.map(t=>{const a=customers.filter(c=>(c.type||'Cliente mostrador')===t);return a.length?`<optgroup label="${t}">${a.map(c=>`<option value="${c.id}">${customerEsc(c.name)}${c.phone?' · '+customerEsc(c.phone):''}</option>`).join('')}</optgroup>`:''}).join('');if(customers.some(c=>c.id===keep))s.value=keep}
function customerSelectForSale(id){const c=customers.find(x=>x.id===id);if(!c)return;document.getElementById('saleName').value=c.name||'';document.getElementById('salePhone').value=c.phone||'';document.getElementById('saleAddress').value=c.address||'';document.getElementById('salePayment').value=c.payment||'Efectivo';salePreview()}
function customerSetup(){document.getElementById('menuCustomers').onclick=showCustomers;document.getElementById('customerSaveBtn').onclick=customerUpsert;document.getElementById('customerCancelBtn').onclick=customerClear;document.getElementById('customerSearch').oninput=customerRender;document.querySelectorAll('.customerTabs button').forEach(b=>b.onclick=()=>{customerTypeFilter=b.dataset.type;customerRender()});const s=document.getElementById('saleCustomer');if(s)s.onchange=()=>{if(s.value)customerSelectForSale(s.value)};customerFillSaleSelect();customerRender()}
setTimeout(customerSetup,80);