let inventory=JSON.parse(localStorage.getItem('ivettInventory')||'{}');let invNotes=JSON.parse(localStorage.getItem('ivettInvNotes')||'[]');let invLog=JSON.parse(localStorage.getItem('ivettInvLog')||'[]');
function invKey(c,n){return c+'||'+n}function invSave(){localStorage.setItem('ivettInventory',JSON.stringify(inventory));localStorage.setItem('ivettInvNotes',JSON.stringify(invNotes));localStorage.setItem('ivettInvLog',JSON.stringify(invLog));if(typeof scheduleCloud==='function')scheduleCloud()}
function invProducts(){return Object.entries(data).flatMap(([c,a])=>a.map(x=>({category:c,name:x[0],price:x[1]})))}
function invInitProduct(c,n,qty=0,unit='kg',min=0){const k=invKey(c,n);if(!inventory[k])inventory[k]={qty:Number(qty)||0,unit:unit||'kg',min:Number(min)||0,updated:new Date().toISOString()};return inventory[k]}
function invStatus(m){const e=document.getElementById('invStatus');if(!e)return;e.textContent=m;clearTimeout(invStatus.t);invStatus.t=setTimeout(()=>e.textContent='',2500)}
function showInventory(){document.getElementById('catalogPanel').classList.add('hidden');document.getElementById('promoPanel').classList.add('hidden');document.getElementById('inventoryPanel').classList.remove('hidden');document.getElementById('sheet').classList.add('hidden');document.getElementById('promoSheet').classList.add('hidden');document.querySelectorAll('.mi').forEach(x=>x.classList.remove('active'));document.getElementById('menuInventory').classList.add('active');invRender()}
function invRender(){const q=(document.getElementById('invSearch')?.value||'').toLowerCase(),e=document.getElementById('inventoryRows');if(!e)return;e.innerHTML='';invProducts().filter(p=>p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)).forEach(p=>{const v=invInitProduct(p.category,p.name),r=document.createElement('div');r.className='invrow'+(v.qty<=v.min?' low':'');r.innerHTML=`<div><b>${p.name}</b><small>${p.category}</small></div><input class="invqty" type="number" step="0.01" value="${v.qty}"><select class="invunit"><option>kg</option><option>pieza</option><option>caja</option><option>paquete</option><option>litro</option></select><input class="invmin" type="number" step="0.01" value="${v.min}"><button class="invplus">＋ Entrada</button>`;r.querySelector('.invunit').value=v.unit;r.querySelector('.invqty').onchange=x=>{v.qty=Number(x.target.value)||0;v.updated=new Date().toISOString();invSave();invRender()};r.querySelector('.invunit').onchange=x=>{v.unit=x.target.value;invSave()};r.querySelector('.invmin').onchange=x=>{v.min=Number(x.target.value)||0;invSave();invRender()};r.querySelector('.invplus').onclick=()=>{const a=prompt(`Cantidad que entra de ${p.name}:`);if(a===null)return;const n=Number(a);if(!Number.isFinite(n)||n<=0)return;v.qty+=n;v.updated=new Date().toISOString();invLog.unshift({date:new Date().toISOString(),type:'ENTRADA',category:p.category,name:p.name,qty:n,unit:v.unit});invSave();invRender();invStatus('Entrada registrada')};e.appendChild(r)});invRenderNotes();invRenderLog()}
function invRenderNotes(){const e=document.getElementById('invNotes');if(!e)return;e.innerHTML=invNotes.slice(0,30).map((n,i)=>`<div class="invnote"><b>${new Date(n.date).toLocaleString('es-MX')}</b><span>${n.text}</span><button data-i="${i}">×</button></div>`).join('');e.querySelectorAll('button').forEach(b=>b.onclick=()=>{invNotes.splice(Number(b.dataset.i),1);invSave();invRenderNotes()})}
function invRenderLog(){const e=document.getElementById('invLog');if(!e)return;e.innerHTML=invLog.slice(0,60).map(x=>`<div class="invlog"><span>${new Date(x.date).toLocaleString('es-MX')}</span><b>${x.type}</b><span>${x.name}</span><strong>+${x.qty} ${x.unit}</strong></div>`).join('')}
function invRegisterNewProduct(){const c=document.getElementById('invNewCat').value,n=document.getElementById('invNewName').value.trim(),p=Number(document.getElementById('invNewPrice').value),q=Number(document.getElementById('invNewQty').value)||0,u=document.getElementById('invNewUnit').value;if(!n)return invStatus('Escribe el nombre del producto');if(data[c].some(x=>x[0].toLowerCase()===n.toLowerCase()))return invStatus('Ese producto ya existe');data[c].push([n,Number.isFinite(p)?p:0]);save();invInitProduct(c,n,q,u,0);invLog.unshift({date:new Date().toISOString(),type:'ALTA',category:c,name:n,qty:q,unit:u});invSave();document.getElementById('invNewName').value='';document.getElementById('invNewPrice').value='';document.getElementById('invNewQty').value='';render();invRender();invStatus('Producto dado de alta y ligado al catálogo')}
function invSetup(){const m=document.getElementById('menuInventory');if(!m)return;m.onclick=showInventory;const s=document.getElementById('invSearch');if(s)s.oninput=invRender;document.getElementById('invAddNote').onclick=()=>{const t=document.getElementById('invNoteText'),v=t.value.trim();if(!v)return;invNotes.unshift({date:new Date().toISOString(),text:v});t.value='';invSave();invRenderNotes()};document.getElementById('invRegister').onclick=invRegisterNewProduct;const sel=document.getElementById('invNewCat');sel.innerHTML=Object.keys(data).map(c=>`<option>${c}</option>`).join('');invProducts().forEach(p=>invInitProduct(p.category,p.name));invSave()}
setTimeout(invSetup,0);