const promoDefault={title:'Arma tu Paquete!!!',price:175,choose:4,subtitle:'de la siguiente lista',items:[['Fresa','1 charola'],['Piña miel','1 pza'],['Uva verde','1/2 kg'],['Melón chino','1 pza'],['Cereza','1/2 kg'],['Papaya','1 pza'],['Bluberry','1 charola'],['Naranja sin semilla','1 1/2 kg'],['Plátano','2 kg']]};
let promo=JSON.parse(localStorage.getItem('ivettPromo')||JSON.stringify(promoDefault)),viewMode='catalog';
function savePromo(){localStorage.setItem('ivettPromo',JSON.stringify(promo))}
function allProducts(){return Object.entries(data).flatMap(([category,items])=>items.filter(([name])=>!isHidden(category,name)).map(x=>x[0])).filter((x,i,a)=>a.indexOf(x)===i)}
function promoOptions(){const s=document.getElementById('promoProduct'),v=s.value;s.innerHTML='<option value="">Selecciona un artículo…</option>'+allProducts().map(n=>`<option>${n}</option>`).join('');if(allProducts().includes(v))s.value=v}
function promoRender(){document.getElementById('promoTitle').value=promo.title;document.getElementById('promoPrice').value=promo.price;document.getElementById('promoChoose').value=promo.choose;document.getElementById('promoSubtitle').value=promo.subtitle;document.getElementById('promoHeadline').textContent=promo.title;document.getElementById('promoPriceView').textContent='$'+promo.price;document.getElementById('promoChooseView').textContent=promo.choose;document.getElementById('promoSubtitleView').textContent=promo.subtitle;promoOptions();const ed=document.getElementById('promoEditor'),g=document.getElementById('promoGrid');ed.innerHTML='';g.innerHTML='';promo.items.filter(it=>allProducts().includes(it[0])).forEach((it,i)=>{const realIndex=promo.items.findIndex(x=>x===it),r=document.createElement('div');r.className='promoEditRow';r.innerHTML=`<img src="${img(it[0])}"><input value="${it[0].replace(/"/g,'&quot;')}" readonly><input value="${it[1].replace(/"/g,'&quot;')}"><button>×</button>`;r.querySelectorAll('input')[1].onchange=e=>{promo.items[realIndex][1]=e.target.value;savePromo();promoRender()};r.querySelector('button').onclick=()=>{promo.items.splice(realIndex,1);savePromo();promoRender()};ed.appendChild(r);const c=document.createElement('div');c.className='promoCard';c.innerHTML=`<img src="${img(it[0])}" crossorigin="anonymous"><div class="pcname">${it[0]}</div><div class="pcqty">${it[1]}</div>`;g.appendChild(c)})}
function setViewMode(m){viewMode=m;const pr=m==='promo';document.getElementById('catalogPanel').classList.toggle('hidden',pr);document.getElementById('promoPanel').classList.toggle('hidden',!pr);document.getElementById('sheet').classList.toggle('hidden',pr);document.getElementById('promoSheet').classList.toggle('hidden',!pr);document.getElementById('menuCatalog').classList.toggle('active',!pr);document.getElementById('menuPromo').classList.toggle('active',pr);document.getElementById('cats').classList.toggle('hidden',pr);if(pr)promoRender()}
document.getElementById('menuCatalog').onclick=()=>setViewMode('catalog');document.getElementById('menuPromo').onclick=()=>setViewMode('promo');
[['promoTitle','title'],['promoPrice','price'],['promoChoose','choose'],['promoSubtitle','subtitle']].forEach(([id,k])=>document.getElementById(id).onchange=e=>{promo[k]=(k==='price'||k==='choose')?Number(e.target.value||0):e.target.value;savePromo();promoRender()});
document.getElementById('promoAddBtn').onclick=()=>{const n=document.getElementById('promoProduct').value,q=document.getElementById('promoQty').value.trim()||'1 pza';if(!n)return;if(promo.items.some(x=>x[0]===n))return;if(promo.items.length>=10)return;promo.items.push([n,q]);document.getElementById('promoQty').value='';savePromo();promoRender()};
document.getElementById('preview').onclick=()=>document.getElementById(viewMode==='promo'?'promoSheet':'sheet').scrollIntoView({behavior:'smooth'});
document.getElementById('jpg').onclick=async()=>{const el=document.getElementById(viewMode==='promo'?'promoSheet':'sheet'),t=document.createElement('div');t.className='export-toast';t.textContent='Generando JPG en alta calidad…';document.body.appendChild(t);try{if(document.fonts&&document.fonts.ready)await document.fonts.ready;await new Promise(r=>setTimeout(r,180));const c=await html2canvas(el,{scale:2,useCORS:true,allowTaint:true,backgroundColor:'#fffdf8',logging:false,width:1536,height:1024,windowWidth:1536,windowHeight:1024}),a=document.createElement('a');a.href=c.toDataURL('image/jpeg',.98);a.download=viewMode==='promo'?'Fruteria_Ivett_Promocion.jpg':'Fruteria_Ivett_'+cat.replace(/[^A-Za-z0-9]+/g,'_')+'_Alta_Calidad.jpg';a.click();t.textContent='JPG listo'}catch(e){console.error(e);t.textContent='No se pudo generar el JPG'}finally{setTimeout(()=>t.remove(),1600)}};
promoRender();