let sales=JSON.parse(localStorage.getItem('ivettSales')||'[]'),saleItems=[];
function saleSave(){localStorage.setItem('ivettSales',JSON.stringify(sales))}function saleMoney(n){return '$'+Number(n||0).toFixed(2)}
function showSales(){['catalogPanel','promoPanel','inventoryPanel','customersPanel'].forEach(id=>document.getElementById(id)?.classList.add('hidden'));['sheet','promoSheet','saleNote'].forEach(id=>document.getElementById(id)?.classList.add('hidden'));document.getElementById('salesPanel').classList.remove('hidden');document.querySelectorAll('.mi').forEach(x=>x.classList.remove('active'));document.getElementById('menuSales').classList.add('active');saleFillProducts();if(typeof customerFillSaleSelect==='function')customerFillSaleSelect();saleRender()}
function saleFillProducts(){const s=document.getElementById('saleProduct');s.innerHTML=invProducts().map((p,i)=>`<option value="${i}">${p.name} · ${p.category} · ${saleMoney(p.price)}</option>`).join('')}
function saleAdd(){const p=invProducts()[Number(document.getElementById('saleProduct').value)],q=Number(document.getElementById('saleQty').value);if(!p||!q||q<=0)return;const v=invInitProduct(p.category,p.name);if(q>v.qty&&!confirm(`Solo hay ${v.qty} ${v.unit} de ${p.name}. ¿Agregar de todos modos?`))return;saleItems.push({...p,qty:q,unit:v.unit});document.getElementById('saleQty').value='';saleRender()}
function saleRender(){const e=document.getElementById('saleItems');e.innerHTML=saleItems.map((x,i)=>`<div class="saleitem"><span>${x.name}<small>${x.qty} ${x.unit} × ${saleMoney(x.price)}</small></span><b>${saleMoney(x.qty*x.price)}</b><button data-i="${i}">×</button></div>`).join('');e.querySelectorAll('button').forEach(b=>b.onclick=()=>{saleItems.splice(+b.dataset.i,1);saleRender()});document.getElementById('saleTotal').textContent=saleMoney(saleItems.reduce((a,x)=>a+x.qty*x.price,0));salePreview()}
function salePreview(){const g=id=>document.getElementById(id)?.value||'',body=saleItems.map(x=>`<tr><td>${x.name}</td><td>${x.qty} ${x.unit}</td><td>${saleMoney(x.price)}</td><td>${saleMoney(x.qty*x.price)}</td></tr>`).join('');document.getElementById('saleNote').innerHTML=`<div class="saleLogo"><span class="logoimg"></span><div><h1>Frutería <b>Ivett</b></h1><p>Fruta fresca, sabor natural</p></div></div><h2>NOTA DE VENTA</h2><div class="saleClient"><p><b>Nombre:</b> ${g('saleName')}</p><p><b>No. de celular:</b> ${g('salePhone')}</p><p class="wide"><b>Domicilio:</b> ${g('saleAddress')}</p><p><b>Fecha:</b> ${g('saleDate')}</p><p><b>Forma de pago:</b> ${g('salePayment')}</p></div><table><thead><tr><th>Producto</th><th>Cantidad</th><th>P. unitario</th><th>Importe</th></tr></thead><tbody>${body}</tbody></table><div class="saleGrand">TOTAL: ${document.getElementById('saleTotal').textContent}</div><div class="saleThanks">¡Gracias por su compra!<br><small>Pedidos por WhatsApp · 33 3204 3831</small></div>`}
function saleIssue(){if(!saleItems.length)return alert('Agrega al menos un producto.');const name=document.getElementById('saleName').value.trim();if(!name)return alert('Escribe el nombre del cliente.');for(const x of saleItems){const v=invInitProduct(x.category,x.name);v.qty=Math.max(0,v.qty-x.qty);v.updated=new Date().toISOString();invLog.unshift({date:new Date().toISOString(),type:'VENTA',category:x.category,name:x.name,qty:-x.qty,unit:x.unit})}const rec={folio:String(Date.now()).slice(-7),customerId:document.getElementById('saleCustomer')?.value||'',date:document.getElementById('saleDate').value,name,phone:document.getElementById('salePhone').value,address:document.getElementById('saleAddress').value,payment:document.getElementById('salePayment').value,items:saleItems,total:saleItems.reduce((a,x)=>a+x.qty*x.price,0)};sales.unshift(rec);saleSave();invSave();document.getElementById('saleNote').classList.remove('hidden');salePreview();window.print();document.getElementById('saleNote').classList.add('hidden');saleItems=[];saleRender();alert('Nota expedida, ligada al cliente y existencias descontadas del inventario.')}
function saleSetup(){document.getElementById('menuSales').onclick=showSales;document.getElementById('saleAdd').onclick=saleAdd;document.getElementById('saleIssue').onclick=saleIssue;document.getElementById('saleDate').value=new Date().toISOString().slice(0,10);['saleName','salePhone','saleAddress','saleDate','salePayment'].forEach(id=>document.getElementById(id).addEventListener('input',salePreview));saleFillProducts();saleRender()}
setTimeout(saleSetup,50);